### ISSUE TITLE
讨论关于任务完成时间

### ISSUE THREAD

**Issue by kkmikako** [UESTC-FEDOG/new-world-website#1]
整个要求一共有十二个任务，我们团队做的就是七到十一，一共五个任务，我看了下时间，因为任务不仅需要我们去完成自己的代码，还要求我们提交自己的任务笔记，所以我觉得我们要在3月31号以前把所有的写代码的工作给完成，时间可以分配给每个任务或多或少，每个任务确定一个最迟的截止时间，定时上传完成的任务

因为基础相关知识忘得快差不多了，我自己会在这三天里面把1-6个任务给写完，每天写两个，完成以后也可以提交上去，个人时间安排大概是这样的：
- 14-16，完成任务1-6
- 17-18，完成任务7
- 19-20，完成任务8
- 21-22，完成任务9
- 22-24，完成任务10
- 25-26，完成任务11

个人想的每个任务的代码提交截止时间如下：
- 3.17：任务七
- 3.20：任务八
- 3.23：任务九
- 3.26：任务十
- 3.30：任务十一

这样的话有个问题就是我的任务7，8 会完成的时间相对较晚，而且也没有预留review的时间，希望大家大家能写出自己的时间大致安排，以及对于截止时间的想法，从team-page开发这个事情上来看，强制要求一个提交的截止时间还是很有必要的

**Comment by ylc395** [comment]
这个安排我兹词

**Comment by ylc395** [comment]
为每个任务开一个仓库吧。这就有劳你了@kkmikako

每个人各自先独立完成每个任务（在自己的分支上），并互相批改代码。代码改好后，选一个最好的分支合并到master分支上。

**Comment by yinyanli** [comment]
我也支持上面的任务时间安排，在截止时间前提交
